### PR TITLE
fix(moleculer-db-adapter-mongoose): remove connecting error/warning, Fix #361

### LINKED ISSUE #361: [Mongoose adapter] Error in the log when starting two or more services
Error in the log when starting two or more services (if services use one connection).

Packages:
```
"moleculer": "0.14.29",
"moleculer-db": "0.8.23",
"moleculer-db-adapter-mongoose": "0.9.2",
"mongoose": "6.11.3"
```
Example:
```js
const { ServiceBroker } = require('moleculer');
const DbService = require('moleculer-db');
const MongooseAdapter = require('moleculer-db-adapter-mongoose');
const mongoose = require('mongoose');

const MONGO_URI = 'mongodb://localhost:27017/test'

const serviceA = {
  name: 'A',
  mixins: [DbService],
  adapter: new MongooseAdapter(MONGO_URI),
  model: mongoose.model('A', new mongoose.Schema({})),
};

const serviceB = {
  name: 'B',
  mixins: [DbService],
  adapter: new MongooseAdapter(MONGO_URI),
  model: mongoose.model('B', new mongoose.Schema({})),
};

const broker = new ServiceBroker();
broker.createService(serviceA);
broker.createService(serviceB);

broker
  .start()
  .delay(5 * 1000)
  .then(() => broker.stop())
  .catch((err) => console.log('Error', err));
```

Log:
mongoose1
mongoose2

Bugs:
- Service B instead of waiting for the connection throws an exception and starts reconnecting;
- Service B does not write a successful connection message to the log.

### PR DESCRIPTION
**Pull request by thib3113**
This PR is here to fix #361 . 

It seems that, after calling on time `mongoose.connect` . The "connection" promise is available in "mongoose.connection.$initialConnection"

So, the promise will wait one, or the other . 

and I reuse the commons objects from mongoose to setup current connection, events handler, and other . 

tested with mongoose@^6 and mongoose@^7

### CODE REVIEW

File: packages/moleculer-db-adapter-mongoose/src/index.js [hunk 1]
```diff
@@ -67,17 +67,15 @@ class MongooseDbAdapter {
...
 
 		if (this.model) {
-
 			/* istanbul ignore next */
 			if (mongoose.connection.readyState == 1) {
 				this.db = mongoose.connection;
 				return Promise.resolve();
 			} else if (mongoose.connection.readyState == 2) {
-				conn = Promise.resolve(mongoose.connection);
+				conn = mongoose.connection.$initialConnection;
```
Comment (icebob) [inline packages/moleculer-db-adapter-mongoose/src/index.js:75]: It looks it's an internal variable and I don't like that we use it.

@vkarpov15 could you help us? Can we use the `$initialConnection` or is there any better option to get the already connected connection?

**Comment by thib3113** [comment]
@icebob I have a question about the "ideology" . 

Each services will pass an adapter ? what if they are not the same ? 
if I understand the "Database per service pattern", each adapter need to be different ? ( in theory ) . 

So, in theory, we need to focus on supporting "differents urls" and not supposing each node will use the same url ?

So, my fixes, and previous ones goes in the false direction ? because checking mongoose.connection.readyState is a non sens if we need to recreate a new connection each time ? 
( we need to don't reuse existing connection, but each times create a new one ? and maybe only reuse the previous one if someone doesn't follow the pattern ? )

( actually, if I correctly understand, we will always reuse the previous connection if already exist  )

**Comment by icebob** [comment]
Each service would have a unique/different connection string to a database. It's not mandatory but we should support it.
For example:
- ServiceA uses MongoDB with mongoose and connects to `mongodb://first-mongo:27017/service-a`
- ServiceB uses MongoDB with mongoose but connects to a different server `mongodb://second-mongo:27017/service-b`
- and just for fun, ServiceC uses PostgreSQL with Sequelize and connects to `postgres://pg-server:5432/service-c`

So yeah, every service should create a new connection because they can use different Mongo servers.

In the new database service I'm using [a memory storage](https://github.com/moleculerjs/database/blob/master/src/adapters/mongodb.js#L81) to store the connection by connection string. So if I start multiple services on one node and all of them uses the same connection string, only one connection will be opened. But this service supports only Mongo adapter, not mongoose.

**Comment by thib3113** [comment]
ok, so I think we have a problem ... 

Because : 
```
if (mongoose.connection.readyState == 1) {
  this.db = mongoose.connection;
  return Promise.resolve();
} else if (mongoose.connection.readyState == 2) {
  conn = mongoose.connection.$initialConnection;
} else {
  conn = mongoose.connect(this.uri, this.opts);
}
```
can't be used, because the two firsts `if` will reuse the previous connection . ( so not possible to use a differents urls )

Also, models can't be used in this cases [[documentation](https://mongoosejs.com/docs/connections.html#multiple_connections)] . 

Because models are created like this : 
```
    model: mongoose.model("Post", mongoose.Schema({
        title: { type: String },
        content: { type: String },
        votes: { type: Number, default: 0}
    }))
```
they are using the default mongoose connection ( so, maybe not the actual connection )


---

So, actually I'm pretty sure we can't use two differents mongodb server on the same node (and I add more defects on this) ... 

So, I'm not sure about what to do ... 
 - need to rewrite a big part to allow real separates connection ? (but will need to create a new major because changes of models => schema ...)
 - use the global mongoose connection => but so we are using a "database per nodes" pattern

( also, I know about your new database service . Maybe you just want to deprecate this one ? or other ideas ? )

File: packages/moleculer-db-adapter-mongoose/src/index.js (hunk 1 above)
Comment (icebob) [reply packages/moleculer-db-adapter-mongoose/src/index.js:75]: Thank you Valeri!
@thib3113 could you change the PR based on this comment, plz?

Comment (thib3113) [reply packages/moleculer-db-adapter-mongoose/src/index.js:75]: @icebob ok . but what about the rest of the PR ? did we continue in this direction ( so, we don't handle two different url ) . Or we rework this part to handle differents url ?

**Comment by icebob** [comment]
It means, with mongoose we can't cover the "database per service"

File: packages/moleculer-db-adapter-mongoose/src/index.js (hunk 1 above)
Comment (icebob) [reply packages/moleculer-db-adapter-mongoose/src/index.js:75]: If we can't solve it, keep the current logic which doesn't support different urls.

**Comment by thib3113** [comment]
@icebob  yes . but not with the actual implementation . We need to create a new connection each time, and don't use the global one . 

Also, creating models directly ( so passing models from the settings, instead of schema ), is not possible, because creating a model will link it to the global instance . 
( the user need to pass a Schema, and we need to instanciate the model, or create a function that will be called with the connection, and user can create models )

**Comment by thib3113** [comment]
@icebob PR updated . I will check to start a new PR to do the correction about the db per service
